export const GET_TRS_INFO = 'GET_TRS_INFO';
export const GET_TRS_INFO_SUCCESS = 'GET_TRS_INFO_SUCCESS';
export const GET_TRS_INFO_FAILED = 'GET_TRS_INFO_FAILED';

export const GET_REBUS_INFO = 'GET_REBUS_INFO';
export const GET_REBUS_INFO_SUCCESS = 'GET_REBUS_INFO_SUCCESS';
export const GET_REBUS_INFO_FAILED = 'GET_REBUS_INFO_FAILED';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const GET_TRS_GLOBALE_INFO = 'GET_TRS_GLOBALE_INFO';
export const GET_TRS_GLOBALE_INFO_SUCCESS = 'GET_TRS_GLOBALE_INFO_SUCCESS';
export const GET_TRS_GLOBALE_INFO_FAILED = 'GET_TRS_GLOBALE_INFO_FAILED';

export const GET_ABSENT_INFO = 'GET_ABSENT_INFO';
export const GET_ABSENT_INFO_SUCCESS = 'GET_ABSENT_INFO_SUCCESS';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';

export const ADD_NEW_QRQC = 'ADD_NEW_QRQC';
export const ADD_NEW_QRQC_SUCCESS = 'ADD_NEW_QRQC_SUCCESS';
export const GET_QRQC_LIST = 'GET_QRQC_LIST';
export const GET_QRQC_LIST_SUCCESS = 'GET_QRQC_LIST_SUCCESS';
